// --- State Management: Enable/Disable the extension ---
async function updateIcon(isEnabled) {
    const iconPath = isEnabled ? "assets/icon48.png" : "assets/icon48-disabled.png";
    chrome.action.setIcon({ path: iconPath });
    const badgeText = isEnabled ? 'ON' : '';
    await chrome.action.setBadgeText({ text: badgeText });
    await chrome.action.setBadgeBackgroundColor({ color: isEnabled ? '#4CAF50' : '#757575' });
}

chrome.runtime.onInstalled.addListener(() => {
    chrome.storage.sync.set({ isEnabled: false });
    updateIcon(false);
    chrome.runtime.openOptionsPage();
});

chrome.action.onClicked.addListener(async (tab) => {
    const { isEnabled } = await chrome.storage.sync.get('isEnabled');
    const newState = !isEnabled;
    await chrome.storage.sync.set({ isEnabled: newState });
    updateIcon(newState);
});

// --- API Logic with Port Communication ---
let portFromCS;

chrome.runtime.onConnect.addListener((port) => {
    if (port.name === "verifeye_port") {
        portFromCS = port;
        portFromCS.onMessage.addListener(async (request) => {
            if (request.action === 'analyzeImage') {
                try {
                    const result = await analyzeImageWithGemini(request.imageUrl);
                    portFromCS.postMessage({ action: 'showResult', result: result, imageUrl: request.imageUrl });
                } catch (error) {
                    console.error("Background Error:", error.message);
                    portFromCS.postMessage({ action: 'showError', error: error.message, imageUrl: request.imageUrl });
                }
            }
        });
        port.onDisconnect.addListener(() => {
            portFromCS = null;
        });
    }
});

async function analyzeImageWithGemini(imageUrl) {
    const { apiKey } = await chrome.storage.sync.get('apiKey');
    if (!apiKey) throw new Error("API Key not found.");

    const MODEL_NAME = "gemini-flash-latest";
    const API_URL = `https://generativelanguage.googleapis.com/v1beta/models/${MODEL_NAME}:generateContent?key=${apiKey}`;
    
    const prompt = "Analyze this image and determine the probability (from 0 to 100) that it was generated by AI. Respond with only the number, nothing else.";

    let imageResponse;
    try {
        const controller = new AbortController();
        const timeoutId = setTimeout(() => controller.abort(), 7000); // 7-second timeout
        imageResponse = await fetch(imageUrl, { signal: controller.signal });
        clearTimeout(timeoutId);
    } catch (e) {
        throw new Error("Cannot fetch image (CORS or network issue).");
    }
    
    if (!imageResponse.ok) throw new Error("Image URL not accessible.");
    
    const imageBuffer = await imageResponse.arrayBuffer();
    const base64ImageData = btoa(String.fromCharCode(...new Uint8Array(imageBuffer)));

    const apiResponse = await fetch(API_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
            "contents": [{ "parts": [
                { "text": prompt },
                { "inline_data": { "mime_type": imageResponse.headers.get('Content-Type') || 'image/jpeg', "data": base64ImageData } }
            ]}],
            "safetySettings": [
                { "category": "HARM_CATEGORY_HARASSMENT", "threshold": "BLOCK_NONE" },
                { "category": "HARM_CATEGORY_HATE_SPEECH", "threshold": "BLOCK_NONE" },
                { "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT", "threshold": "BLOCK_NONE" },
                { "category": "HARM_CATEGORY_DANGEROUS_CONTENT", "threshold": "BLOCK_NONE" }
            ]
        })
    });

    const responseData = await apiResponse.json();

    if (!apiResponse.ok) {
        throw new Error(responseData.error?.message || `API Error`);
    }
    if (!responseData.candidates || responseData.candidates[0].finishReason === 'SAFETY') {
        throw new Error("Blocked by API safety filter.");
    }
    if (!responseData.candidates[0].content) {
        throw new Error("API returned no content.");
    }

    return responseData.candidates[0].content.parts[0].text;
}