/**
 * VerifEye - Optional Gemini Multimodal Cloud API Client
 * Used when user enables Cloud or Hybrid mode and configures an API key.
 */

export async function analyzeImageWithGemini(apiKey, base64ImageData, mimeType = 'image/jpeg', modelName = 'gemini-1.5-flash') {
    if (!apiKey) {
        throw new Error("No Gemini API key configured.");
    }

    const API_URL = `https://generativelanguage.googleapis.com/v1beta/models/${modelName}:generateContent?key=${apiKey}`;
    
    const prompt = `You are an expert AI image forensics analyst. Analyze this image and determine the probability (from 0 to 100) that it was generated by an AI model (such as Stable Diffusion, Midjourney, DALL-E, Flux, Imagen, etc.).
Respond strictly in JSON format with two keys:
"probability": an integer between 0 and 100 (where 0 means definitely authentic camera photo / human art, and 100 means definitely AI generated),
"reasons": an array of up to 2 brief forensic observations.
Example: {"probability": 85, "reasons": ["Unnatural hand anatomy", "Diffusion texture smoothing"]}`;

    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 12000); // 12-second timeout

    try {
        const response = await fetch(API_URL, {
            method: 'POST',
            signal: controller.signal,
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                "contents": [{
                    "parts": [
                        { "text": prompt },
                        { "inline_data": { "mime_type": mimeType, "data": base64ImageData } }
                    ]
                }],
                "generationConfig": {
                    "temperature": 0.1,
                    "responseMimeType": "application/json"
                },
                "safetySettings": [
                    { "category": "HARM_CATEGORY_HARASSMENT", "threshold": "BLOCK_NONE" },
                    { "category": "HARM_CATEGORY_HATE_SPEECH", "threshold": "BLOCK_NONE" },
                    { "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT", "threshold": "BLOCK_NONE" },
                    { "category": "HARM_CATEGORY_DANGEROUS_CONTENT", "threshold": "BLOCK_NONE" }
                ]
            })
        });

        clearTimeout(timeoutId);

        if (!response.ok) {
            const errData = await response.json().catch(() => ({}));
            throw new Error(errData.error?.message || `API error (${response.status})`);
        }

        const data = await response.json();

        if (!data.candidates || data.candidates.length === 0 || !data.candidates[0].content) {
            throw new Error("API returned no response content.");
        }

        const rawText = data.candidates[0].content.parts[0].text;
        
        // Parse JSON response
        try {
            const parsed = JSON.parse(rawText);
            const prob = Math.min(100, Math.max(0, parseInt(parsed.probability, 10) || 50));
            return {
                probability: prob,
                reasons: Array.isArray(parsed.reasons) ? parsed.reasons : [],
                engine: 'cloud_gemini'
            };
        } catch (e) {
            // Fallback regex if JSON parsing fails
            const numMatch = rawText.match(/\b\d{1,3}\b/);
            const prob = numMatch ? Math.min(100, Math.max(0, parseInt(numMatch[0], 10))) : 50;
            return {
                probability: prob,
                reasons: ['Cloud multimodal visual analysis'],
                engine: 'cloud_gemini'
            };
        }
    } catch (err) {
        clearTimeout(timeoutId);
        throw err;
    }
}

/**
 * Quick validation helper to test an API key without large payload
 */
export async function testGeminiApiKey(apiKey, modelName = 'gemini-1.5-flash') {
    if (!apiKey) throw new Error("API key cannot be empty");

    const API_URL = `https://generativelanguage.googleapis.com/v1beta/models/${modelName}:generateContent?key=${apiKey}`;
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 8000);

    try {
        const response = await fetch(API_URL, {
            method: 'POST',
            signal: controller.signal,
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                "contents": [{
                    "parts": [{ "text": "Ping" }]
                }],
                "generationConfig": { "maxOutputTokens": 2 }
            })
        });

        clearTimeout(timeoutId);

        if (!response.ok) {
            const errData = await response.json().catch(() => ({}));
            throw new Error(errData.error?.message || `API error (${response.status})`);
        }

        return { success: true };
    } catch (err) {
        clearTimeout(timeoutId);
        throw err;
    }
}
